### PR TITLE
first upload

### PR DESCRIPTION
**Pull request by nickjamesridgway**
I added index.html

### CODE REVIEW

**Comment by ESThing64** [comment]
Okay, this is good.

**Review by BossyLemon0 — COMMENTED** [review]
well done

**Comment by BossyLemon0** [comment]
great

**Comment by JTMJFX** [comment]
This is good!

**Review by ESThing64 — APPROVED** [review]
good to go.

**Review by BossyLemon0 — APPROVED** [review]
well done x2

**Review by JTMJFX — APPROVED** [review]
this is good

**Comment by ESThing64** [comment]
and its done

**Pull request merged**
